### PR TITLE
Added overtime round support for game outcome panel

### PR DESCRIPTION
**Pull request by simonszu**
A first fix for https://github.com/kinduff/csgo_exporter/issues/40

### CODE REVIEW

**Comment by kinduff** [comment]
Hey there @simonszu, thanks for your contribution.

So I tested this and there seems to be an issue:
- I won my last game, `type="wins"` yields 16
- The rounds yielded by `type="rounds"` is 21

We have `16/21` which is `0.7`, we have a rule that between `[0 - 1]` we consider it a loss. So my last game, with this change, looks like a loss.

My guess is, no matter what type of game you have, you will always win if you have more than the half of the rounds won. Can this assumption apply for FaceIt matches too?

Sadly, the API does not return the matches won or loss by the enemy team, neither the score.

**Comment by simonszu** [comment]
I think this assumption can apply. I have checked out the rules and it seems that each time an overtime applies, there are an additional 10 rounds added to the game, with the first team getting 5 wins wins the game. If the first overtime ends in a draw, an additional overtime is added, but you will win if you have more than the half of the rounds won. 
This also applies to other leagues with overtime, the only change is the amount of rounds per half of overtime. Some leagues have best of 6, other leagues have best of 10, but this does not affect your proposed metrics.

**Comment by kinduff** [comment]
Can you modify the dashboard so it reflects this idea? :pray:

**Comment by simonszu** [comment]
I think this should work now. At least it was showing the correct values for all the (official league) matches i played yesterday.

**Comment by kinduff** [comment]
@simonszu Thanks a lot for your contribution. Really sorry for taking this long. Given the new short rounds in CS:GO, I had the opportunity to test this. Works as expected.

**Pull request merged**
