### PR TITLE
Fix datasource variable usage in the dashboard

### PR DESCRIPTION
**Pull request by colega**

### CODE REVIEW

**Comment by kinduff** [comment]
@colega Thanks a lot for your contribution.

I'm wondering, what's the advantage of having this field declared?

**Comment by colega** [comment]
Oh, sorry, the commit message wasn't added as PR description 🤦 

It was:
> Some "dashboard" fields were set to null, which broke the queries on the import.

This field is present in most of the panes, which work properly, but where it's set to `null`, Grafana sets the datasource to _the example Grafana datasource_ when dashboard is imported, and the Prometheus query is lost forever.

Setting `"dashboard"` to the one selected during the import makes everything work just fine.

**Comment by kinduff** [comment]
Perfect, thanks a lot for your contribution. Merging this.

**Comment by kinduff** [comment]
@all-contributors please add @simonszu for content

**Comment by kinduff** [comment]
@all-contributors please add @colega for content

**Pull request merged**
